fail_fast: true

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-yaml
      exclude: 'docs/.*'
    - id: trailing-whitespace
      exclude: 'docs/.*'
    - id: name-tests-test
      args: ["--pytest-test-first"]
      exclude: 'docs/.*'
    - id: check-added-large-files
      args: ["--maxkb=50"]
    - id: check-case-conflict
      exclude: 'docs/.*'
    - id: check-shebang-scripts-are-executable
      exclude: 'docs/.*'

- repo: https://github.com/asottile/pyupgrade
  rev: v3.21.2
  hooks:
    - id: pyupgrade

- repo: https://github.com/gitleaks/gitleaks
  rev: v8.24.2
  hooks:
    - id: gitleaks
      exclude: '.*/tests/.*'

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.10
  hooks:
    - id: ruff-check
      types_or: [ python, pyi ]
      args: [ --fix ]
    - id: ruff-format
      types_or: [ python, pyi ]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.14.1
  hooks:
    - id: mypy
      args: [--ignore-missing-imports]
      additional_dependencies:
        - "pydantic>=2.8.2"
